/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// modals/examModal.ts
var examModal_exports = {};
__export(examModal_exports, {
  ExamModal: () => ExamModal
});
var import_obsidian6, ExamModal;
var init_examModal = __esm({
  "modals/examModal.ts"() {
    import_obsidian6 = require("obsidian");
    ExamModal = class extends import_obsidian6.Modal {
      constructor(app, unit, onSubmit) {
        super(app);
        this.examData = {};
        this.unit = unit;
        this.onSubmit = onSubmit;
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.createEl("h2", { text: `Add Exam for ${this.unit.name}` });
        new import_obsidian6.Setting(contentEl).setName("Exam Title").setDesc("Name or type of the exam").addText((text) => text.setPlaceholder("e.g., Midterm Exam, Final Exam").onChange((value) => {
          this.examData.title = value;
        }));
        new import_obsidian6.Setting(contentEl).setName("Date").setDesc("Exam date").addText((text) => {
          text.inputEl.type = "date";
          text.setPlaceholder("YYYY-MM-DD").onChange((value) => {
            if (value) {
              const parts = value.split("-");
              const dateObj = new Date(parseInt(parts[0]), parseInt(parts[1]) - 1, parseInt(parts[2]));
              this.examData.date = dateObj.getTime();
            }
          });
        });
        new import_obsidian6.Setting(contentEl).setName("Time").setDesc("Exam time (24-hour format)").addText((text) => {
          text.inputEl.type = "time";
          text.setPlaceholder("HH:MM").setValue("09:00").onChange((value) => {
            this.examData.time = value;
          });
        });
        new import_obsidian6.Setting(contentEl).setName("Location").setDesc("Exam room or building (optional)").addText((text) => text.setPlaceholder("e.g., Room 301, Building A").onChange((value) => {
          this.examData.location = value || void 0;
        }));
        new import_obsidian6.Setting(contentEl).setName("Topics").setDesc("Comma-separated list of exam topics").addTextArea((textArea) => {
          textArea.setPlaceholder("e.g., Data Structures, Algorithms, Complexity Analysis").onChange((value) => {
            this.examData.topics = value.split(",").map((t) => t.trim()).filter((t) => t.length > 0);
          });
          textArea.inputEl.rows = 4;
          textArea.inputEl.style.width = "100%";
        });
        const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
        const submitBtn = buttonContainer.createEl("button", {
          text: "Add Exam",
          cls: "mod-cta"
        });
        const addAnotherBtn = buttonContainer.createEl("button", {
          text: "Add & Another",
          attr: { style: "margin-right: 10px;" }
        });
        const handleSubmit = (shouldClose) => {
          if (!this.examData.title || !this.examData.date) {
            new import_obsidian6.Notice("Please fill in exam title and date");
            return;
          }
          if (!this.examData.time) {
            this.examData.time = "09:00";
          }
          if (!this.examData.topics || this.examData.topics.length === 0) {
            this.examData.topics = ["General Review"];
          }
          this.onSubmit(this.examData);
          if (shouldClose) {
            this.close();
          } else {
            new import_obsidian6.Notice("Exam added! Add another.");
            this.examData.title = "";
            this.examData.topics = [];
            this.onOpen();
          }
        };
        addAnotherBtn.addEventListener("click", () => handleSubmit(false));
        submitBtn.addEventListener("click", () => handleSubmit(true));
        const cancelBtn = buttonContainer.createEl("button", {
          text: "Cancel"
        });
        cancelBtn.addEventListener("click", () => {
          this.close();
        });
      }
      onClose() {
        const { contentEl } = this;
        contentEl.empty();
      }
    };
  }
});

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BetterTaskPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian12 = require("obsidian");

// goalManager.ts
var import_obsidian = require("obsidian");
var GoalManager = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async createGoal(title, description) {
    const id = Date.now().toString(36) + Math.random().toString(36).substr(2);
    const newGoal = {
      id,
      title,
      description,
      type: "habit",
      // Defaulting to habit if not provided, though types.ts says it's required
      createdAt: Date.now(),
      status: "active"
    };
    this.plugin.saveToUndoStack("goal_created", { goalId: id });
    this.plugin.data.goals.push(newGoal);
    await this.plugin.savePluginData();
    this.plugin.app.workspace.trigger("better-task:data-change");
    new import_obsidian.Notice("Goal created successfully!");
    return newGoal;
  }
  async editGoal(goalId, updates) {
    const goalIndex = this.plugin.data.goals.findIndex((g) => g.id === goalId);
    if (goalIndex === -1)
      return null;
    const originalGoal = { ...this.plugin.data.goals[goalIndex] };
    this.plugin.saveToUndoStack("goal_edited", { goal: originalGoal });
    const updatedGoal = { ...originalGoal, ...updates };
    this.plugin.data.goals[goalIndex] = updatedGoal;
    await this.plugin.savePluginData();
    this.plugin.app.workspace.trigger("better-task:data-change");
    new import_obsidian.Notice("Goal updated!");
    return updatedGoal;
  }
  async deleteGoal(goalId) {
    const goal = this.plugin.data.goals.find((g) => g.id === goalId);
    const tasks = this.plugin.data.dailyTasks.filter((t) => t.goalId === goalId);
    if (goal) {
      this.plugin.saveToUndoStack("goal_deleted", {
        goal: { ...goal },
        tasks: tasks.map((t) => ({ ...t }))
      });
    }
    this.plugin.data.goals = this.plugin.data.goals.filter((g) => g.id !== goalId);
    this.plugin.data.dailyTasks = this.plugin.data.dailyTasks.filter((t) => t.goalId !== goalId);
    await this.plugin.savePluginData();
    this.plugin.app.workspace.trigger("better-task:data-change");
    new import_obsidian.Notice("Goal deleted.");
  }
  async markGoalAsCompleted(goalId) {
    const goal = this.plugin.data.goals.find((g) => g.id === goalId);
    if (goal) {
      goal.status = "completed";
      goal.completedDate = Date.now();
      await this.plugin.savePluginData();
      this.plugin.app.workspace.trigger("better-task:data-change");
      new import_obsidian.Notice(`Goal "${goal.title}" marked as completed! \u{1F389}`);
    }
  }
  async archiveGoal(goalId) {
    const goal = this.plugin.data.goals.find((g) => g.id === goalId);
    if (goal) {
      goal.status = "archived";
      await this.plugin.savePluginData();
      this.plugin.app.workspace.trigger("better-task:data-change");
      new import_obsidian.Notice(`Goal "${goal.title}" archived.`);
    }
  }
  getGoalStreak(goalId) {
    const completions = this.plugin.data.completions.filter((c) => c.goalId === goalId).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    if (completions.length === 0)
      return 0;
    let streak = 0;
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    let currentDate = new Date(today);
    const completedToday = completions.some((c) => c.date === currentDate.toISOString().split("T")[0]);
    if (!completedToday) {
      currentDate.setDate(currentDate.getDate() - 1);
      const completedYesterday = completions.some((c) => c.date === currentDate.toISOString().split("T")[0]);
      if (!completedYesterday) {
        return 0;
      }
    }
    currentDate = new Date(today);
    if (!completedToday) {
      currentDate.setDate(currentDate.getDate() - 1);
    }
    while (true) {
      const dateStr = currentDate.toISOString().split("T")[0];
      const hasCompletion = completions.some((c) => c.date === dateStr);
      if (hasCompletion) {
        streak++;
        currentDate.setDate(currentDate.getDate() - 1);
      } else {
        break;
      }
    }
    return streak;
  }
  getDaysSinceLastCompletion(goalId) {
    const completions = this.plugin.data.completions.filter((c) => c.goalId === goalId).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    if (completions.length === 0)
      return -1;
    const lastCompletion = completions[0];
    const lastDate = new Date(lastCompletion.date);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const diffTime = Math.abs(today.getTime() - lastDate.getTime());
    const diffDays = Math.ceil(diffTime / (1e3 * 60 * 60 * 24));
    return diffDays;
  }
};

// taskManager.ts
var import_obsidian2 = require("obsidian");
var TaskManager = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async createDailyTask(goalId, taskData) {
    const id = Date.now().toString(36) + Math.random().toString(36).substr(2);
    const newTask = {
      id,
      goalId,
      title: taskData.title || "New Task",
      description: taskData.description,
      daysOfWeek: taskData.daysOfWeek || [0, 1, 2, 3, 4, 5, 6],
      startTime: taskData.startTime || "09:00",
      endTime: taskData.endTime || "10:00",
      reminderMinutes: taskData.reminderMinutes,
      createdAt: Date.now()
    };
    this.plugin.saveToUndoStack("daily_task_created", { taskId: id });
    this.plugin.data.dailyTasks.push(newTask);
    await this.plugin.savePluginData();
    this.plugin.app.workspace.trigger("better-task:data-change");
    new import_obsidian2.Notice("Daily task created successfully!");
    return newTask;
  }
  async createFreeTask(taskData) {
    const id = Date.now().toString(36) + Math.random().toString(36).substr(2);
    const newTask = {
      id,
      title: taskData.title || "New Task",
      description: taskData.description,
      dueDate: taskData.dueDate,
      dueTime: taskData.dueTime,
      isCompleted: false,
      reminderMinutes: taskData.reminderMinutes,
      createdAt: Date.now()
    };
    this.plugin.saveToUndoStack("free_task_created", { taskId: id });
    this.plugin.data.freeTasks.push(newTask);
    await this.plugin.savePluginData();
    this.plugin.app.workspace.trigger("better-task:data-change");
    new import_obsidian2.Notice("Task created successfully!");
    return newTask;
  }
  async completeTask(taskId, goalId, notes) {
    const freeTaskBefore = this.plugin.data.freeTasks.find((t) => t.id === taskId);
    this.plugin.saveToUndoStack("task_completed", {
      taskId,
      freeTask: freeTaskBefore ? { ...freeTaskBefore } : null
    });
    const completion = {
      id: Date.now().toString(36) + Math.random().toString(36).substr(2),
      taskId,
      goalId,
      completedAt: Date.now(),
      date: new Date().toISOString().split("T")[0],
      notes
    };
    this.plugin.data.completions.push(completion);
    const freeTask = this.plugin.data.freeTasks.find((t) => t.id === taskId);
    if (freeTask) {
      freeTask.isCompleted = true;
      freeTask.completedAt = Date.now();
    }
    await this.plugin.savePluginData();
    this.plugin.app.workspace.trigger("better-task:data-change");
    new import_obsidian2.Notice("Task completed! \u{1F389}");
  }
  async uncompleteTask(taskId) {
    const today = new Date().toISOString().split("T")[0];
    const completionIndex = this.plugin.data.completions.findIndex(
      (c) => c.taskId === taskId && c.date === today
    );
    if (completionIndex !== -1) {
      this.plugin.data.completions.splice(completionIndex, 1);
    }
    const freeTask = this.plugin.data.freeTasks.find((t) => t.id === taskId);
    if (freeTask) {
      freeTask.isCompleted = false;
      freeTask.completedAt = void 0;
    }
    await this.plugin.savePluginData();
    this.plugin.app.workspace.trigger("better-task:data-change");
    new import_obsidian2.Notice("Task marked as incomplete.");
  }
  getTasksForToday() {
    const now = (0, import_obsidian2.moment)();
    const dayOfWeek = now.day();
    const dateString = now.format("YYYY-MM-DD");
    const currentTime = now.hour() * 100 + now.minute();
    const dailyTasks = this.plugin.data.dailyTasks.filter((task) => {
      if (!task.daysOfWeek.includes(dayOfWeek))
        return false;
      const goal = this.plugin.data.goals.find((g) => g.id === task.goalId);
      const status = (goal == null ? void 0 : goal.status) || "active";
      if (!goal || status !== "active")
        return false;
      const createdMoment = (0, import_obsidian2.moment)(task.createdAt);
      if (now.isBefore(createdMoment, "day"))
        return false;
      if (now.isSame(createdMoment, "day")) {
        const taskEndTime = parseInt(task.endTime.replace(":", ""));
        if (currentTime >= taskEndTime)
          return false;
      }
      return true;
    });
    const freeTasks = this.plugin.data.freeTasks.filter(
      (task) => !task.isCompleted && (!task.dueDate || (0, import_obsidian2.moment)(task.dueDate).format("YYYY-MM-DD") === dateString)
    );
    return { dailyTasks, freeTasks };
  }
  isTaskCompletedToday(taskId) {
    const today = new Date().toISOString().split("T")[0];
    return this.plugin.data.completions.some(
      (c) => c.taskId === taskId && c.date === today
    );
  }
  checkTaskConflicts(newTask) {
    if (!newTask.daysOfWeek || !newTask.startTime || !newTask.endTime) {
      return [];
    }
    const newStart = parseInt(newTask.startTime.replace(":", ""));
    const newEnd = parseInt(newTask.endTime.replace(":", ""));
    return this.plugin.data.dailyTasks.filter((existingTask) => {
      if (existingTask.id === newTask.id)
        return false;
      const daysOverlap = existingTask.daysOfWeek.some((day) => {
        var _a;
        return (_a = newTask.daysOfWeek) == null ? void 0 : _a.includes(day);
      });
      if (!daysOverlap)
        return false;
      const existingStart = parseInt(existingTask.startTime.replace(":", ""));
      const existingEnd = parseInt(existingTask.endTime.replace(":", ""));
      return newStart < existingEnd && newEnd > existingStart;
    });
  }
};

// modals/goalModal.ts
var import_obsidian3 = require("obsidian");
var GoalModal = class extends import_obsidian3.Modal {
  constructor(app, onSubmit, initialData) {
    super(app);
    this.onSubmit = onSubmit;
    this.initialData = initialData;
    this.result = initialData ? { ...initialData } : { title: "", description: "" };
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", { text: this.initialData ? "Edit Goal" : "Create New Goal" });
    new import_obsidian3.Setting(contentEl).setName("Title").addText((text) => text.setValue(this.result.title).onChange((value) => {
      this.result.title = value;
    }));
    new import_obsidian3.Setting(contentEl).setName("Description").addTextArea((text) => text.setValue(this.result.description).onChange((value) => {
      this.result.description = value;
    }));
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("Create").setCta().onClick(() => {
      this.close();
      this.onSubmit(this.result);
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// modals/taskModal.ts
var import_obsidian4 = require("obsidian");
var TaskModal = class extends import_obsidian4.Modal {
  constructor(plugin, type, goals, onSubmit) {
    super(plugin.app);
    this.plugin = plugin;
    this.type = type;
    this.goals = goals;
    this.onSubmit = onSubmit;
    this.result = {
      title: "",
      description: "",
      daysOfWeek: [],
      reminderMinutes: 15
    };
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", { text: `Create ${this.type === "daily" ? "Daily" : "Quick"} Task` });
    if (this.type === "daily") {
      if (this.goals.length > 0) {
        this.result.goalId = this.goals[0].id;
        new import_obsidian4.Setting(contentEl).setName("Goal").addDropdown((dropDown) => {
          this.goals.forEach((goal) => {
            dropDown.addOption(goal.id, goal.title);
          });
          dropDown.setValue(this.goals[0].id);
          dropDown.onChange((value) => {
            this.result.goalId = value;
          });
        });
      } else {
        new import_obsidian4.Setting(contentEl).setName("Goal").setDesc("No goals found. Please create a goal first.");
      }
    }
    new import_obsidian4.Setting(contentEl).setName("Title").addText((text) => text.onChange((value) => {
      this.result.title = value;
    }));
    new import_obsidian4.Setting(contentEl).setName("Description").addTextArea((text) => text.onChange((value) => {
      this.result.description = value;
    }));
    if (this.type === "daily") {
      this.createDailyTaskFields(contentEl);
    } else {
      this.createFreeTaskFields(contentEl);
    }
    new import_obsidian4.Setting(contentEl).setName("Reminder (minutes before)").addText((text) => text.setValue("15").onChange((value) => {
      this.result.reminderMinutes = parseInt(value, 10) || 0;
    }));
    new import_obsidian4.Setting(contentEl).addButton((btn) => btn.setButtonText("Create & Add Another").onClick(() => {
      this.onSubmit(this.result);
      this.result.title = "";
      this.result.description = "";
      new import_obsidian4.Notice("Task created! Add another.");
      this.contentEl.empty();
      this.onOpen();
    })).addButton((btn) => btn.setButtonText("Create").setCta().onClick(() => {
      this.close();
      this.onSubmit(this.result);
    }));
  }
  createDailyTaskFields(contentEl) {
    const warningEl = contentEl.createDiv({ cls: "task-conflict-warning" });
    warningEl.style.display = "none";
    warningEl.style.color = "var(--text-error)";
    warningEl.style.marginBottom = "15px";
    warningEl.style.padding = "10px";
    warningEl.style.backgroundColor = "rgba(233, 62, 62, 0.1)";
    warningEl.style.borderRadius = "5px";
    warningEl.style.fontSize = "0.9em";
    const validateConflicts = () => {
      const plugin = this.app.plugins.plugins["better-task"];
      if (plugin && plugin.taskManager) {
        const conflicts = plugin.taskManager.checkTaskConflicts(this.result);
        if (conflicts.length > 0) {
          warningEl.style.display = "block";
          const conflictTitles = conflicts.map((t) => t.title).join(", ");
          warningEl.setText(`\u26A0\uFE0F Conflict with: ${conflictTitles}`);
        } else {
          warningEl.style.display = "none";
        }
      }
    };
    const daysDiv = contentEl.createDiv();
    daysDiv.createEl("h3", { text: "Days of Week" });
    const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
    if (!this.result.daysOfWeek || this.result.daysOfWeek.length === 0) {
      this.result.daysOfWeek = [0, 1, 2, 3, 4, 5, 6];
    }
    days.forEach((day, index) => {
      var _a;
      const dayContainer = daysDiv.createDiv({ cls: "day-checkbox" });
      const cb = dayContainer.createEl("input", { type: "checkbox" });
      cb.id = `day-${index}`;
      cb.checked = ((_a = this.result.daysOfWeek) == null ? void 0 : _a.includes(index)) || false;
      cb.onchange = (e) => {
        var _a2, _b, _c, _d;
        const checked = e.target.checked;
        if (checked) {
          if (!((_a2 = this.result.daysOfWeek) == null ? void 0 : _a2.includes(index))) {
            (_b = this.result.daysOfWeek) == null ? void 0 : _b.push(index);
          }
        } else {
          this.result.daysOfWeek = (_c = this.result.daysOfWeek) == null ? void 0 : _c.filter((d) => d !== index);
        }
        (_d = this.result.daysOfWeek) == null ? void 0 : _d.sort();
        validateConflicts();
      };
      dayContainer.createEl("label", { text: day, attr: { for: `day-${index}` } });
      dayContainer.style.display = "inline-block";
      dayContainer.style.marginRight = "10px";
    });
    new import_obsidian4.Setting(contentEl).setName("Start Time").addText((text) => {
      text.inputEl.type = "time";
      text.setPlaceholder("HH:MM").onChange((value) => {
        this.result.startTime = value;
        validateConflicts();
      });
    });
    new import_obsidian4.Setting(contentEl).setName("End Time").addText((text) => {
      text.inputEl.type = "time";
      text.setPlaceholder("HH:MM").onChange((value) => {
        this.result.endTime = value;
        validateConflicts();
      });
    });
  }
  createFreeTaskFields(contentEl) {
    new import_obsidian4.Setting(contentEl).setName("Due Date").addText((text) => {
      text.inputEl.type = "date";
      text.setPlaceholder("YYYY-MM-DD").onChange((value) => {
        if (value) {
          const parts = value.split("-");
          const dateObj = new Date(parseInt(parts[0]), parseInt(parts[1]) - 1, parseInt(parts[2]));
          this.result.dueDate = dateObj.getTime();
        } else {
          this.result.dueDate = void 0;
        }
      });
    });
    new import_obsidian4.Setting(contentEl).setName("Due Time").addText((text) => {
      text.inputEl.type = "time";
      text.setPlaceholder("HH:MM").onChange((value) => {
        this.result.dueTime = value;
      });
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// views/dashboardView.ts
var import_obsidian7 = require("obsidian");

// modals/goalDetailsModal.ts
var import_obsidian5 = require("obsidian");
var GoalDetailsModal = class extends import_obsidian5.Modal {
  constructor(plugin, goal) {
    super(plugin.app);
    this.plugin = plugin;
    this.goal = goal;
    this.tasks = this.plugin.data.dailyTasks.filter((t) => t.goalId === goal.id);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("goal-details-modal");
    const header = contentEl.createDiv({ cls: "goal-dashboard-header" });
    header.createEl("h2", { text: this.goal.title });
    if (this.goal.description) {
      header.createEl("p", { text: this.goal.description, cls: "goal-desc-muted" });
    }
    const layout = contentEl.createDiv({ cls: "goal-dashboard-layout" });
    const sidebar = layout.createDiv({ cls: "goal-dashboard-sidebar" });
    const consistency = this.plugin.analyticsManager ? this.plugin.analyticsManager.getCompletionRateByGoal(this.goal.id) : 0;
    const streak = this.plugin.goalManager.getGoalStreak(this.goal.id);
    const healthCircle = sidebar.createDiv({ cls: "goal-health-ring" });
    healthCircle.createDiv({ text: `${Math.round(consistency)}%`, cls: "health-value" });
    healthCircle.createDiv({ text: "consistency", cls: "health-label" });
    let color = "var(--text-error)";
    if (consistency >= 80)
      color = "var(--text-success)";
    else if (consistency >= 50)
      color = "var(--text-warning)";
    healthCircle.style.borderColor = color;
    const statsList = sidebar.createDiv({ cls: "goal-mini-stats" });
    statsList.createDiv({ cls: "mini-stat" }).innerHTML = `<span>Streak</span> <strong>${streak}d</strong>`;
    const daysSince = this.plugin.goalManager.getDaysSinceLastCompletion(this.goal.id);
    statsList.createDiv({ cls: "mini-stat" }).innerHTML = `<span>Last Active</span> <strong>${daysSince === 0 ? "Today" : daysSince + "d ago"}</strong>`;
    const main = layout.createDiv({ cls: "goal-dashboard-main" });
    main.createEl("h3", { text: "Daily Schedule" });
    const taskList = main.createDiv({ cls: "goal-task-list-modern" });
    if (this.tasks.length === 0) {
      taskList.createEl("p", { text: "No recurring tasks for this goal.", cls: "empty-hint" });
    } else {
      this.tasks.forEach((task) => {
        const item = taskList.createDiv({ cls: "goal-task-item" });
        const info = item.createDiv({ cls: "task-item-info" });
        info.createEl("div", { text: task.title, cls: "task-title" });
        info.createEl("div", { text: `${task.startTime} - ${task.endTime}`, cls: "task-time" });
        const days = item.createDiv({ cls: "task-days-row" });
        ["S", "M", "T", "W", "T", "F", "S"].forEach((d, i) => {
          const day = days.createEl("span", { text: d, cls: "day-bubble" });
          if (task.daysOfWeek.includes(i))
            day.addClass("active");
        });
      });
    }
    const footer = contentEl.createDiv({ cls: "goal-dashboard-footer" });
    const addTaskBtn = footer.createEl("button", { text: "+ New Daily Task", cls: "mod-cta" });
    addTaskBtn.onclick = () => {
      this.close();
      new TaskModal(this.plugin, "daily", [this.goal], async (result) => {
        if (result.goalId)
          await this.plugin.taskManager.createDailyTask(result.goalId, result);
      }).open();
    };
    const editBtn = footer.createEl("button", { text: "Edit Goal" });
    editBtn.onclick = () => {
      this.close();
      new GoalModal(this.app, async (result) => {
        await this.plugin.goalManager.editGoal(this.goal.id, result);
      }, { title: this.goal.title, description: this.goal.description }).open();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// views/dashboardView.ts
var DASHBOARD_VIEW_TYPE = "better-task-dashboard";
var DashboardView = class extends import_obsidian7.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.showAllExams = false;
    this.currentCalendarMonth = new Date();
    this.selectedCalendarDay = null;
    this.plugin = plugin;
  }
  getViewType() {
    return DASHBOARD_VIEW_TYPE;
  }
  getDisplayText() {
    return "Better Task";
  }
  getIcon() {
    return "check-circle";
  }
  async onOpen() {
    this.render();
    this.registerEvent(this.plugin.app.workspace.on("better-task:data-change", () => {
      this.render();
    }));
  }
  async onClose() {
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    const wrapper = container.createEl("div", { cls: "better-task-dashboard" });
    this.renderHeader(wrapper);
    this.renderActionButtons(wrapper);
    this.renderTodaysTasks(wrapper);
    if (this.plugin.data.settings.studentMode) {
      try {
        this.renderStudentMode(wrapper);
      } catch (error) {
        console.error("Error rendering student mode:", error);
        const errorSection = wrapper.createEl("div", { cls: "dashboard-section" });
        errorSection.createEl("h2", { text: "\u{1F393} Student Dashboard" });
        errorSection.createEl("p", {
          text: "Error loading student mode. Please check console for details.",
          cls: "error-message"
        });
      }
    }
    this.renderQuickTasks(wrapper);
    this.renderGoalsOverview(wrapper);
    this.renderCalendar(wrapper);
    this.renderAnalytics(wrapper);
  }
  renderHeader(container) {
    const headerEl = container.createEl("div", { cls: "dashboard-header" });
    headerEl.createEl("h1", { text: "Better Task Dashboard" });
    headerEl.createEl("h3", { text: (0, import_obsidian7.moment)().format("dddd, MMMM Do YYYY") });
  }
  renderTodaysTasks(container) {
    const section = container.createEl("div", { cls: "dashboard-section" });
    section.createEl("h2", { text: "Today's Tasks" });
    const { dailyTasks } = this.plugin.taskManager.getTasksForToday();
    if (dailyTasks.length === 0) {
      const emptyState = section.createEl("div", { cls: "empty-state-with-action" });
      emptyState.createEl("p", { text: "\u{1F4C5} No daily tasks scheduled for today." });
      emptyState.createEl("p", { text: "Daily tasks are recurring activities linked to your goals.", cls: "empty-hint" });
      const btn = emptyState.createEl("button", { text: "+ Create Daily Task", cls: "empty-action-btn" });
      btn.addEventListener("click", () => {
        this.plugin.app.commands.executeCommandById("better-task:create-daily-task");
      });
      return;
    }
    const list = section.createEl("div", { cls: "task-list" });
    dailyTasks.forEach((task) => {
      const taskEl = list.createEl("div", { cls: "task-item" });
      const isCompleted = this.plugin.taskManager.isTaskCompletedToday(task.id);
      if (isCompleted)
        taskEl.addClass("completed");
      const checkbox = taskEl.createEl("input", { type: "checkbox" });
      checkbox.checked = isCompleted;
      checkbox.addEventListener("change", async () => {
        if (checkbox.checked) {
          await this.plugin.taskManager.completeTask(task.id, task.goalId);
          this.render();
        } else {
          await this.plugin.taskManager.uncompleteTask(task.id);
          this.render();
        }
      });
      const content = taskEl.createEl("div", { cls: "task-content" });
      content.createEl("span", { text: task.title, cls: "task-title" });
      content.createEl("span", { text: `${task.startTime} - ${task.endTime}`, cls: "task-time" });
      const goal = this.plugin.data.goals.find((g) => g.id === task.goalId);
      if (goal) {
        content.createEl("span", { text: goal.title, cls: "goal-tag" });
      }
    });
  }
  renderQuickTasks(container) {
    const section = container.createEl("div", { cls: "dashboard-section" });
    section.createEl("h2", { text: "Quick Tasks" });
    const incompleteFreeTasks = this.plugin.data.freeTasks.filter((t) => !t.isCompleted);
    if (incompleteFreeTasks.length === 0) {
      const emptyState = section.createEl("div", { cls: "empty-state-with-action" });
      emptyState.createEl("p", { text: "\u2705 No pending quick tasks." });
      emptyState.createEl("p", { text: "Quick tasks are one-off to-dos you need to complete.", cls: "empty-hint" });
      const btn = emptyState.createEl("button", { text: "+ Create Quick Task", cls: "empty-action-btn" });
      btn.addEventListener("click", () => {
        this.plugin.app.commands.executeCommandById("better-task:create-free-task");
      });
      return;
    }
    const list = section.createEl("div", { cls: "task-list" });
    incompleteFreeTasks.forEach((task) => {
      const taskEl = list.createEl("div", { cls: "task-item" });
      const checkbox = taskEl.createEl("input", { type: "checkbox" });
      checkbox.checked = false;
      checkbox.addEventListener("change", async () => {
        if (checkbox.checked) {
          await this.plugin.taskManager.completeTask(task.id);
          this.render();
        } else {
          await this.plugin.taskManager.uncompleteTask(task.id);
          this.render();
        }
      });
      const content = taskEl.createEl("div", { cls: "task-content" });
      content.createEl("span", { text: task.title, cls: "task-title" });
      if (task.dueTime) {
        content.createEl("span", { text: `Due: ${task.dueTime}`, cls: "task-time" });
      }
    });
  }
  renderGoalsOverview(container) {
    const section = container.createEl("div", { cls: "dashboard-section" });
    section.createEl("h2", { text: "Your Goals" });
    if (this.plugin.data.goals.length === 0) {
      const emptyState = section.createEl("div", { cls: "empty-state-with-action" });
      emptyState.createEl("p", { text: "No goals yet. Let's get started!" });
      emptyState.createEl("p", { text: "Goals are long-term habits or resolutions you want to track.", cls: "empty-hint" });
      const btn = emptyState.createEl("button", { text: "+ Create Your First Goal", cls: "empty-action-btn primary" });
      btn.addEventListener("click", () => {
        this.plugin.app.commands.executeCommandById("better-task:create-goal");
      });
      return;
    }
    const grid = section.createEl("div", { cls: "goals-grid" });
    const activeGoals = this.plugin.data.goals.filter((g) => (g.status || "active") === "active");
    if (activeGoals.length === 0 && this.plugin.data.goals.length > 0) {
      section.createEl("p", { text: "All goals are completed or archived! Great job! \u{1F389}", cls: "empty-hint" });
      return;
    }
    activeGoals.forEach((goal) => {
      const card = grid.createEl("div", { cls: "goal-card interactive-card" });
      if (goal.color) {
        card.style.borderTop = `2px solid ${goal.color}`;
      }
      card.addEventListener("click", () => {
        new GoalDetailsModal(this.plugin, goal).open();
      });
      card.addEventListener("contextmenu", (event) => {
        const menu = new import_obsidian7.Menu();
        menu.addItem((item) => {
          item.setTitle("Mark as Complete").setIcon("check").onClick(async () => {
            await this.plugin.goalManager.markGoalAsCompleted(goal.id);
          });
        });
        menu.addItem((item) => {
          item.setTitle("Archive").setIcon("archive").onClick(async () => {
            await this.plugin.goalManager.archiveGoal(goal.id);
          });
        });
        menu.addSeparator();
        menu.addItem((item) => {
          item.setTitle("Edit Goal").setIcon("pencil").onClick(() => {
            new GoalModal(this.plugin.app, async (result) => {
              await this.plugin.goalManager.editGoal(goal.id, result);
            }, { title: goal.title, description: goal.description }).open();
          });
        });
        menu.addItem((item) => {
          item.setTitle("Delete Goal").setIcon("trash").onClick(async () => {
            if (confirm(`Delete "${goal.title}"?`)) {
              await this.plugin.goalManager.deleteGoal(goal.id);
            }
          });
        });
        menu.showAtMouseEvent(event);
      });
      const header = card.createEl("div", { cls: "goal-card-header" });
      header.createEl("h3", { text: goal.title });
      const consistency = this.plugin.analyticsManager.getCompletionRateByGoal(goal.id);
      const healthBar = card.createEl("div", { cls: "mini-health-bar" });
      const fill = healthBar.createEl("div", { cls: "mini-health-fill" });
      let colorClass = "health-low";
      if (consistency >= 80)
        colorClass = "health-high";
      else if (consistency >= 50)
        colorClass = "health-medium";
      fill.addClass(colorClass);
      fill.style.width = `${Math.max(consistency, 5)}%`;
      const footer = card.createEl("div", { cls: "goal-card-footer" });
      const streak = this.plugin.goalManager.getGoalStreak(goal.id);
      if (streak > 0) {
        footer.createEl("span", { text: `\u{1F525} ${streak}`, cls: "streak-count" });
      }
      footer.createEl("span", { text: `${Math.round(consistency)}%`, cls: "health-percent" });
      const actions = card.createEl("div", { cls: "goal-actions" });
      const editBtn = actions.createEl("button", { cls: "goal-action-btn" });
      (0, import_obsidian7.setIcon)(editBtn, "pencil");
      editBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        new GoalModal(this.plugin.app, async (result) => {
          await this.plugin.goalManager.editGoal(goal.id, result);
        }, { title: goal.title, description: goal.description }).open();
      });
      const completeBtn = actions.createEl("button", { cls: "goal-action-btn" });
      (0, import_obsidian7.setIcon)(completeBtn, "check");
      completeBtn.setAttr("title", "Mark as Complete");
      completeBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        await this.plugin.goalManager.markGoalAsCompleted(goal.id);
      });
      const deleteBtn = actions.createEl("button", { cls: "goal-action-btn" });
      (0, import_obsidian7.setIcon)(deleteBtn, "trash");
      deleteBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        if (confirm(`Delete "${goal.title}"?`)) {
          await this.plugin.goalManager.deleteGoal(goal.id);
        }
      });
    });
  }
  renderAnalytics(container) {
    const section = container.createEl("details", { cls: "dashboard-section analytics-section" });
    section.setAttribute("open", "");
    const summary = section.createEl("summary");
    summary.createEl("h2", { text: "Insights & Analytics", cls: "inline-header" });
    const statsGrid = section.createEl("div", { cls: "stats-grid" });
    const successCard = statsGrid.createEl("div", { cls: "stat-card" });
    successCard.createEl("h4", { text: "Weekly Score" });
    const successRate = this.plugin.analyticsManager.getWeeklySuccessRate();
    successCard.createEl("div", { text: `${successRate}%`, cls: "stat-value" });
    successCard.createEl("div", { text: "consistency", cls: "stat-label" });
    const streakCard = statsGrid.createEl("div", { cls: "stat-card" });
    streakCard.createEl("h4", { text: "Best Streak" });
    const longestStreak = this.plugin.analyticsManager.getLongestStreakEver();
    streakCard.createEl("div", { text: `${longestStreak} \u{1F525}`, cls: "stat-value" });
    streakCard.createEl("div", { text: "all-time record", cls: "stat-label" });
    const attentionCard = statsGrid.createEl("div", { cls: "stat-card focus-card" });
    attentionCard.createEl("h4", { text: "Recent Focus" });
    const activeGoal = this.plugin.analyticsManager.getMostActiveGoal();
    if (activeGoal) {
      attentionCard.createEl("div", { text: activeGoal.title, cls: "stat-value goal-name" });
      attentionCard.createEl("div", { text: "most active this week", cls: "stat-label" });
    } else {
      attentionCard.createEl("div", { text: "N/A", cls: "stat-value" });
      attentionCard.createEl("div", { text: "Start your week!", cls: "stat-label" });
    }
    const activityHistory = this.plugin.analyticsManager.getActivityHistory(7);
    const activitySection = section.createEl("div", { cls: "activity-comparison-section" });
    const activityHeader = activitySection.createDiv({ cls: "activity-header-row" });
    activityHeader.createEl("h4", { text: "Activity Comparison" });
    const legend = activityHeader.createDiv({ cls: "chart-legend" });
    const createdLeg = legend.createDiv({ cls: "legend-item" });
    createdLeg.createDiv({ cls: "legend-color created" });
    createdLeg.createEl("span", { text: "Created" });
    const completedLeg = legend.createDiv({ cls: "legend-item" });
    completedLeg.createDiv({ cls: "legend-color completed" });
    completedLeg.createEl("span", { text: "Completed" });
    const chart = activitySection.createEl("div", { cls: "activity-chart" });
    const maxVal = Math.max(...activityHistory.map((h) => Math.max(h.created, h.completed)), 1);
    activityHistory.forEach((day, i) => {
      const group = chart.createEl("div", { cls: "bar-group" });
      const createdContainer = group.createDiv({ cls: "bar-container created" });
      const cHeight = day.created / maxVal * 100;
      const cBar = createdContainer.createDiv({ cls: "bar created" });
      cBar.style.height = `${Math.max(cHeight, 2)}%`;
      const completedContainer = group.createDiv({ cls: "bar-container completed" });
      const compHeight = day.completed / maxVal * 100;
      const compBar = completedContainer.createDiv({ cls: "bar completed" });
      compBar.style.height = `${Math.max(compHeight, 2)}%`;
      if (i === 6)
        group.addClass("is-today");
    });
  }
  renderActionButtons(container) {
    const section = container.createEl("div", { cls: "dashboard-actions" });
    const newGoalBtn = section.createEl("button", { text: "+ New Goal" });
    newGoalBtn.addEventListener("click", () => {
      this.plugin.app.commands.executeCommandById("better-task:create-goal");
    });
    const newQuickTaskBtn = section.createEl("button", { text: "+ Quick Task" });
    newQuickTaskBtn.addEventListener("click", () => {
      this.plugin.app.commands.executeCommandById("better-task:create-free-task");
    });
    const newDailyTaskBtn = section.createEl("button", { text: "+ Daily Task" });
    newDailyTaskBtn.addEventListener("click", () => {
      this.plugin.app.commands.executeCommandById("better-task:create-daily-task");
    });
    if (this.plugin.data.settings.studentMode) {
      const newUnitBtn = section.createEl("button", { text: "\u{1F393} New Unit" });
      newUnitBtn.addEventListener("click", () => {
        this.plugin.app.commands.executeCommandById("better-task:create-unit");
      });
      const addExamBtn = section.createEl("button", { text: "\u{1F4DD} Add Exam" });
      addExamBtn.addEventListener("click", () => {
        this.plugin.app.commands.executeCommandById("better-task:add-exam");
      });
    }
  }
  renderStudentMode(container) {
    const studentSection = container.createEl("details", { cls: "dashboard-section student-mode-section" });
    studentSection.setAttribute("open", "");
    const summary = studentSection.createEl("summary");
    summary.createEl("h2", { text: "Student Dashboard", cls: "inline-header" });
    this.renderStudentContent(studentSection);
  }
  renderStudentContent(container) {
    const section = container.createEl("div", { cls: "student-subsection" });
    section.createEl("h3", { text: "Current Semester Units" });
    this.renderUnitsGrid(section);
    section.createEl("h3", { text: "Upcoming Exams (Next 30 Days)", cls: "exams-heading" });
    this.renderExamsList(section);
  }
  renderUnitsGrid(container) {
    const currentUnits = this.plugin.studentManager.getCurrentSemesterUnits();
    if (currentUnits.length === 0) {
      const emptyState = container.createEl("div", { cls: "empty-state-with-action" });
      emptyState.createEl("p", { text: "\u{1F4DA} No units registered this semester." });
      emptyState.createEl("p", { text: "Create units to track your courses and exams.", cls: "empty-hint" });
      const btn = emptyState.createEl("button", { text: "+ Create First Unit", cls: "empty-action-btn" });
      btn.addEventListener("click", () => {
        this.plugin.app.commands.executeCommandById("better-task:create-unit");
      });
      return;
    }
    const grid = container.createEl("div", { cls: "units-grid" });
    currentUnits.forEach((unit) => {
      const card = grid.createEl("div", { cls: "unit-card" });
      card.addEventListener("contextmenu", (event) => {
        const menu = new import_obsidian7.Menu();
        menu.addItem((item) => {
          item.setTitle("Mark as Complete").setIcon("check").onClick(async () => {
            await this.plugin.studentManager.markUnitAsCompleted(unit.id);
          });
        });
        menu.addItem((item) => {
          item.setTitle("Archive").setIcon("archive").onClick(async () => {
            await this.plugin.studentManager.archiveUnit(unit.id);
          });
        });
        menu.addSeparator();
        menu.addItem((item) => {
          item.setTitle("Delete Unit").setIcon("trash").onClick(async () => {
            if (confirm(`Delete "${unit.name}"?`)) {
              await this.plugin.studentManager.deleteUnit(unit.id);
            }
          });
        });
        menu.showAtMouseEvent(event);
      });
      const header = card.createEl("div", { cls: "unit-header" });
      header.createEl("h4", { text: unit.name });
      header.createEl("span", { text: unit.code, cls: "unit-code" });
      if (unit.instructor) {
        card.createEl("div", { text: unit.instructor, cls: "unit-instructor" });
      }
      card.createEl("div", { text: `Credits: ${unit.credits}`, cls: "unit-credits" });
      const examCount = unit.exams.length;
      if (examCount > 0) {
        card.createEl("div", { text: `\u{1F4DD} ${examCount} exam${examCount !== 1 ? "s" : ""}`, cls: "unit-exams-count" });
      }
      const actions = card.createEl("div", { cls: "unit-actions", attr: { style: "display: flex; gap: 8px; margin-top: 10px;" } });
      const addExamBtn = actions.createEl("button", { text: "+ Exam", cls: "unit-action-btn" });
      addExamBtn.addEventListener("click", async () => {
        try {
          const { ExamModal: ExamModal2 } = await Promise.resolve().then(() => (init_examModal(), examModal_exports));
          new ExamModal2(this.plugin.app, unit, async (examData) => {
            const exam = await this.plugin.studentManager.addExam(unit.id, examData);
            if (exam) {
              new import_obsidian7.Notice(`Exam "${exam.title}" added to ${unit.name}!`);
              this.render();
            }
          }).open();
        } catch (error) {
          console.error("Error opening ExamModal:", error);
          new import_obsidian7.Notice("Failed to open exam form. Check console for details.");
        }
      });
      const completeBtn = actions.createEl("button", { text: "Complete", cls: "unit-action-btn" });
      completeBtn.addEventListener("click", async () => {
        await this.plugin.studentManager.markUnitAsCompleted(unit.id);
      });
    });
  }
  renderExamsList(container) {
    const toggleContainer = container.createEl("div", { cls: "exam-horizon-toggle", attr: { style: "margin-bottom: 15px; display: flex; align-items: center; gap: 8px; font-size: 0.9em; color: var(--text-muted);" } });
    const toggle = toggleContainer.createEl("input", { type: "checkbox" });
    toggle.checked = this.showAllExams;
    toggle.addEventListener("change", () => {
      this.showAllExams = toggle.checked;
      this.render();
    });
    toggleContainer.createEl("span", { text: "Show all upcoming exams (beyond 30 days)" });
    const daysLookup = this.showAllExams ? 365 : 30;
    const upcomingExams = this.plugin.studentManager.getUpcomingExams(daysLookup);
    if (upcomingExams.length === 0) {
      container.createEl("p", { text: `\u2705 No upcoming exams in the next ${daysLookup} days.`, cls: "empty-state-text" });
      return;
    }
    const list = container.createEl("div", { cls: "exams-list" });
    upcomingExams.forEach((exam) => {
      const examInfo = this.plugin.studentManager.getExamById(exam.id);
      if (!examInfo)
        return;
      const { unit } = examInfo;
      const card = list.createEl("div", { cls: "exam-card" });
      const header = card.createEl("div", { cls: "exam-header" });
      const titleGroup = header.createDiv();
      titleGroup.createEl("h4", { text: exam.title });
      titleGroup.createEl("span", { text: unit.code, cls: "exam-unit-code" });
      const daysUntil = this.plugin.studentManager.getDaysUntilExam(exam);
      const badgeClass = daysUntil <= 7 ? "urgent" : "normal";
      header.createDiv({ text: `${daysUntil} days left`, cls: `countdown-badge ${badgeClass}` });
      const examDate = new Date(exam.date);
      const dateStr = examDate.toLocaleDateString("en-US", { month: "short", day: "numeric" });
      card.createDiv({ text: `${dateStr} at ${exam.time}`, cls: "exam-date-sub" });
      const footer = card.createDiv({ cls: "exam-footer" });
      const studyBtn = footer.createEl("button", { text: "Generate Plan", cls: "study-tasks-btn" });
      studyBtn.addEventListener("click", async () => {
        try {
          const tasks = await this.plugin.studentManager.generateStudyTasks(exam.id);
          new import_obsidian7.Notice(`Generated ${tasks.length} study task${tasks.length !== 1 ? "s" : ""} for ${exam.title}!`);
          this.render();
        } catch (error) {
          console.error("Error generating study tasks:", error);
          new import_obsidian7.Notice("Failed to generate study tasks. Check console for details.");
        }
      });
    });
  }
  renderCalendar(container) {
    const section = container.createEl("details", { cls: "dashboard-section" });
    section.setAttribute("open", "");
    const summary = section.createEl("summary");
    summary.createEl("h2", { text: "\u{1F4C5} Calendar", cls: "inline-header" });
    const year = this.currentCalendarMonth.getFullYear();
    const month = this.currentCalendarMonth.getMonth();
    const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    const header = section.createEl("div", { cls: "calendar-header" });
    const prevBtn = header.createEl("button", { text: "\u25C0", cls: "calendar-nav-btn" });
    header.createEl("h3", { text: `${monthNames[month]} ${year}` });
    const nextBtn = header.createEl("button", { text: "\u25B6", cls: "calendar-nav-btn" });
    prevBtn.addEventListener("click", () => {
      this.currentCalendarMonth = new Date(year, month - 1, 1);
      this.selectedCalendarDay = null;
      this.render();
    });
    nextBtn.addEventListener("click", () => {
      this.currentCalendarMonth = new Date(year, month + 1, 1);
      this.selectedCalendarDay = null;
      this.render();
    });
    const firstDay = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    const today = new Date();
    const todayStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}-${String(today.getDate()).padStart(2, "0")}`;
    const dailyTasks = this.plugin.data.dailyTasks;
    const freeTasks = this.plugin.data.freeTasks;
    const allExams = [];
    for (const unit of this.plugin.data.studentUnits) {
      for (const exam of unit.exams) {
        allExams.push({ title: exam.title, date: exam.date, time: exam.time, unitCode: unit.code });
      }
    }
    const getItemsForDate = (dateStr, dayOfWeek) => {
      const items = [];
      for (const dt of dailyTasks) {
        if (dt.daysOfWeek.includes(dayOfWeek)) {
          const goal = this.plugin.data.goals.find((g) => g.id === dt.goalId);
          const status = (goal == null ? void 0 : goal.status) || "active";
          if (!goal || status !== "active")
            continue;
          const createdMoment = (0, import_obsidian7.moment)(dt.createdAt);
          const checkMoment = (0, import_obsidian7.moment)(dateStr);
          if (checkMoment.isBefore(createdMoment, "day"))
            continue;
          if (checkMoment.isSame(createdMoment, "day")) {
            const taskEndTime = parseInt(dt.endTime.replace(":", ""));
            const creationTime = createdMoment.hour() * 100 + createdMoment.minute();
            if (creationTime >= taskEndTime)
              continue;
          }
          items.push({ type: "daily", label: dt.title, time: `${dt.startTime}\u2013${dt.endTime}` });
        }
      }
      for (const ft of freeTasks) {
        if (ft.dueDate) {
          const ftStr = (0, import_obsidian7.moment)(ft.dueDate).format("YYYY-MM-DD");
          if (ftStr === dateStr) {
            items.push({ type: "free", label: ft.title, time: ft.dueTime || void 0 });
          }
        }
      }
      for (const ex of allExams) {
        const exStr = (0, import_obsidian7.moment)(ex.date).format("YYYY-MM-DD");
        if (exStr === dateStr) {
          items.push({ type: "exam", label: `${ex.title}${ex.unitCode ? " (" + ex.unitCode + ")" : ""}`, time: ex.time });
        }
      }
      return items;
    };
    const grid = section.createEl("div", { cls: "calendar-grid" });
    const dayHeaders = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
    for (const dh of dayHeaders) {
      grid.createEl("div", { text: dh, cls: "calendar-day-header" });
    }
    const prevMonthDays = new Date(year, month, 0).getDate();
    for (let i = firstDay - 1; i >= 0; i--) {
      const cell = grid.createEl("div", { cls: "calendar-day other-month" });
      cell.createEl("span", { text: String(prevMonthDays - i), cls: "calendar-day-number" });
    }
    for (let day = 1; day <= daysInMonth; day++) {
      const dateObj = new Date(year, month, day);
      const dayOfWeek = dateObj.getDay();
      const dateStr = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
      const items = getItemsForDate(dateStr, dayOfWeek);
      const cls = ["calendar-day"];
      if (dateStr === todayStr)
        cls.push("today");
      if (dateStr === this.selectedCalendarDay)
        cls.push("selected");
      const cell = grid.createEl("div", { cls: cls.join(" ") });
      cell.createEl("span", { text: String(day), cls: "calendar-day-number" });
      if (items.length > 0) {
        const dots = cell.createEl("div", { cls: "calendar-dots" });
        const hasDailyTask = items.some((i) => i.type === "daily");
        const hasFreeTask = items.some((i) => i.type === "free");
        const hasExam = items.some((i) => i.type === "exam");
        if (hasDailyTask)
          dots.createEl("span", { cls: "calendar-dot task" });
        if (hasFreeTask)
          dots.createEl("span", { cls: "calendar-dot free" });
        if (hasExam)
          dots.createEl("span", { cls: "calendar-dot exam" });
      }
      cell.addEventListener("click", () => {
        this.selectedCalendarDay = dateStr;
        this.render();
      });
    }
    const totalCells = firstDay + daysInMonth;
    const trailing = (7 - totalCells % 7) % 7;
    for (let i = 1; i <= trailing; i++) {
      const cell = grid.createEl("div", { cls: "calendar-day other-month" });
      cell.createEl("span", { text: String(i), cls: "calendar-day-number" });
    }
    if (this.selectedCalendarDay) {
      const parts = this.selectedCalendarDay.split("-");
      const selDate = new Date(parseInt(parts[0]), parseInt(parts[1]) - 1, parseInt(parts[2]));
      const selDayOfWeek = selDate.getDay();
      const items = getItemsForDate(this.selectedCalendarDay, selDayOfWeek);
      const detail = section.createEl("div", { cls: "calendar-day-detail" });
      const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
      detail.createEl("div", {
        text: `${dayNames[selDayOfWeek]}, ${monthNames[parseInt(parts[1]) - 1]} ${parseInt(parts[2])}, ${parts[0]}`,
        cls: "calendar-detail-header"
      });
      if (items.length === 0) {
        detail.createEl("div", { text: "Nothing scheduled for this day.", cls: "calendar-detail-empty" });
      } else {
        for (const item of items) {
          const row = detail.createEl("div", { cls: "calendar-detail-item" });
          const badgeCls = item.type === "daily" ? "daily" : item.type === "free" ? "free" : "exam";
          const badgeLabel = item.type === "daily" ? "TASK" : item.type === "free" ? "TODO" : "EXAM";
          row.createEl("span", { text: badgeLabel, cls: `cal-type-badge ${badgeCls}` });
          row.createEl("span", { text: item.label });
          if (item.time) {
            row.createEl("span", { text: item.time, cls: "task-time" });
          }
        }
      }
    }
  }
};

// notificationManager.ts
var import_obsidian8 = require("obsidian");

// utils/timeUtils.ts
function subtractMinutes(time, minutes) {
  const [hours, mins] = time.split(":").map(Number);
  const date = new Date();
  date.setHours(hours, mins, 0, 0);
  date.setMinutes(date.getMinutes() - minutes);
  const h = date.getHours().toString().padStart(2, "0");
  const m = date.getMinutes().toString().padStart(2, "0");
  return `${h}:${m}`;
}
function getCurrentTime() {
  const date = new Date();
  const h = date.getHours().toString().padStart(2, "0");
  const m = date.getMinutes().toString().padStart(2, "0");
  return `${h}:${m}`;
}

// utils/dateUtils.ts
function getDateString(date = new Date()) {
  return date.toISOString().split("T")[0];
}

// notificationManager.ts
var NotificationManager = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.notifiedTasks = /* @__PURE__ */ new Set();
    this.notifiedGoals = /* @__PURE__ */ new Set();
    this.checkInterval = null;
    this.requestNotificationPermission();
  }
  requestNotificationPermission() {
    if (!import_obsidian8.Platform.isDesktop)
      return;
    if (Notification.permission === "default") {
      Notification.requestPermission().then((permission) => {
        if (permission === "granted") {
          console.log("Notification permission granted");
        }
      });
    }
  }
  startBackgroundCheck() {
    this.checkReminders();
    this.checkStreaks();
    this.checkInterval = window.setInterval(() => {
      this.checkReminders();
      this.checkStreaks();
    }, 6e4);
  }
  stopBackgroundCheck() {
    if (this.checkInterval) {
      window.clearInterval(this.checkInterval);
      this.checkInterval = null;
    }
  }
  checkReminders() {
    if (!this.plugin.data.settings.notificationsEnabled)
      return;
    const now = getCurrentTime();
    const today = new Date();
    const dayOfWeek = today.getDay();
    const todayStr = getDateString(today);
    this.plugin.data.dailyTasks.forEach((task) => {
      if (task.daysOfWeek.includes(dayOfWeek)) {
        if (task.reminderMinutes) {
          const reminderTime = subtractMinutes(task.startTime, task.reminderMinutes);
          const notificationKey = `${task.id}_${todayStr}`;
          if (now === reminderTime && !this.notifiedTasks.has(notificationKey)) {
            this.sendTaskReminder(task.title, `Starting in ${task.reminderMinutes} minutes`);
            this.notifiedTasks.add(notificationKey);
          }
        }
      }
    });
    this.plugin.data.freeTasks.forEach((task) => {
      if (!task.isCompleted && task.dueDate && task.dueTime && task.reminderMinutes) {
        const taskDueDate = new Date(task.dueDate);
        const taskDateStr = getDateString(taskDueDate);
        if (taskDateStr === todayStr) {
          const reminderTime = subtractMinutes(task.dueTime, task.reminderMinutes);
          if (now === reminderTime && !this.notifiedTasks.has(task.id)) {
            this.sendTaskReminder(task.title, `Due in ${task.reminderMinutes} minutes`);
            this.notifiedTasks.add(task.id);
          }
        }
      }
    });
  }
  checkStreaks() {
    if (!this.plugin.data.settings.notificationsEnabled)
      return;
    const now = new Date();
    if (now.getHours() !== 20)
      return;
    const todayStr = getDateString(now);
    const checkKey = `checked_streaks_${todayStr}`;
    if (this.notifiedGoals.has(checkKey))
      return;
    this.plugin.data.goals.forEach((goal) => {
      if (goal.status === "archived")
        return;
      let daysInvalid = this.plugin.goalManager.getDaysSinceLastCompletion(goal.id);
      if (daysInvalid === -1) {
        const createdDate = new Date(goal.createdAt);
        const diffTime = Math.abs(now.getTime() - createdDate.getTime());
        daysInvalid = Math.ceil(diffTime / (1e3 * 60 * 60 * 24));
      }
      if (daysInvalid >= this.plugin.data.settings.streakWarningDays) {
        this.sendStreakWarning(goal.title, daysInvalid);
      }
    });
    this.notifiedGoals.add(checkKey);
  }
  sendTaskReminder(title, message) {
    new import_obsidian8.Notice(`\u23F0 ${title}: ${message}`);
    if (this.plugin.data.settings.reminderSound) {
      this.playNotificationSound();
    }
    if (Notification.permission === "granted") {
      new Notification("Better Task Reminder", {
        body: `${title}: ${message}`,
        icon: "check-circle"
      });
    }
  }
  sendStreakWarning(goalTitle, daysMissed) {
    const msg = `You haven't completed '${goalTitle}' in ${daysMissed} days!`;
    new import_obsidian8.Notice(`\u26A0\uFE0F ${msg}`, 1e4);
    if (this.plugin.data.settings.reminderSound) {
      this.playNotificationSound();
    }
    if (Notification.permission === "granted") {
      new Notification("Better Task Streak Warning", {
        body: msg,
        requireInteraction: true,
        icon: "alert-triangle"
      });
    }
  }
  playNotificationSound() {
  }
};

// analyticsManager.ts
var AnalyticsManager = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  /**
   * Get total completions from the past N days
   */
  getWeeklyCompletions() {
    const now = Date.now();
    const sevenDaysAgo = now - 7 * 24 * 60 * 60 * 1e3;
    return this.plugin.data.completions.filter(
      (c) => c.completedAt >= sevenDaysAgo
    ).length;
  }
  /**
   * Calculate completion rate for a specific goal over the past 30 days
   * Returns percentage (0-100)
   */
  getCompletionRateByGoal(goalId) {
    const now = Date.now();
    const thirtyDaysAgo = now - 30 * 24 * 60 * 60 * 1e3;
    const dailyTasks = this.plugin.data.dailyTasks.filter((t) => t.goalId === goalId);
    if (dailyTasks.length === 0)
      return 0;
    let expectedCompletions = 0;
    const today = new Date();
    for (let i = 0; i < 30; i++) {
      const checkDate = new Date(today);
      checkDate.setDate(checkDate.getDate() - i);
      const dayOfWeek = checkDate.getDay();
      dailyTasks.forEach((task) => {
        if (task.daysOfWeek.includes(dayOfWeek)) {
          expectedCompletions++;
        }
      });
    }
    if (expectedCompletions === 0)
      return 0;
    const actualCompletions = this.plugin.data.completions.filter(
      (c) => c.goalId === goalId && c.completedAt >= thirtyDaysAgo
    ).length;
    return Math.round(actualCompletions / expectedCompletions * 100);
  }
  /**
   * Find the goal with the highest current streak
   */
  getMostConsistentGoal() {
    if (this.plugin.data.goals.length === 0)
      return null;
    let bestGoal = null;
    let maxStreak = 0;
    this.plugin.data.goals.forEach((goal) => {
      const streak = this.plugin.goalManager.getGoalStreak(goal.id);
      if (streak > maxStreak) {
        maxStreak = streak;
        bestGoal = goal;
      }
    });
    return maxStreak > 0 ? bestGoal : null;
  }
  /**
   * Find the goal with the most days since last completion
   */
  getGoalNeedingAttention() {
    if (this.plugin.data.goals.length === 0)
      return null;
    let needsAttention = null;
    let maxDays = 0;
    this.plugin.data.goals.forEach((goal) => {
      const daysSince = this.plugin.goalManager.getDaysSinceLastCompletion(goal.id);
      if (daysSince > maxDays) {
        maxDays = daysSince;
        needsAttention = goal;
      }
    });
    return maxDays > 0 ? needsAttention : null;
  }
  /**
   * Get completion count for each day in the past N days
   * Returns array of {date, count} objects for heatmap visualization
   */
  getCompletionHeatmap(days) {
    const heatmapData = [];
    const today = new Date();
    for (let i = days - 1; i >= 0; i--) {
      const checkDate = new Date(today);
      checkDate.setDate(checkDate.getDate() - i);
      const dateStr = getDateString(checkDate);
      const count = this.plugin.data.completions.filter(
        (c) => c.date === dateStr
      ).length;
      heatmapData.push({ date: dateStr, count });
    }
    return heatmapData;
  }
  /**
   * Get the longest streak ever achieved across all goals
   */
  getLongestStreakEver() {
    let maxStreak = 0;
    this.plugin.data.goals.forEach((goal) => {
      const completions = this.plugin.data.completions.filter((c) => c.goalId === goal.id).sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
      let currentStreak = 0;
      let previousDate = null;
      completions.forEach((completion) => {
        const completionDate = new Date(completion.date);
        if (!previousDate) {
          currentStreak = 1;
        } else {
          const dayDiff = Math.floor((completionDate.getTime() - previousDate.getTime()) / (1e3 * 60 * 60 * 24));
          if (dayDiff === 1) {
            currentStreak++;
          } else {
            maxStreak = Math.max(maxStreak, currentStreak);
            currentStreak = 1;
          }
        }
        previousDate = completionDate;
      });
      maxStreak = Math.max(maxStreak, currentStreak);
    });
    return maxStreak;
  }
  /**
   * Get percentage of days in the last 7 days with at least one completion
   */
  getWeeklySuccessRate() {
    const today = new Date();
    let successfulDays = 0;
    for (let i = 0; i < 7; i++) {
      const checkDate = new Date(today);
      checkDate.setDate(today.getDate() - i);
      const dateStr = getDateString(checkDate);
      const hasCompletion = this.plugin.data.completions.some((c) => c.date === dateStr);
      if (hasCompletion)
        successfulDays++;
    }
    return Math.round(successfulDays / 7 * 100);
  }
  /**
   * Get creation and completion counts for each of the last 7 days
   */
  getActivityHistory(days = 7) {
    const history = [];
    const today = new Date();
    for (let i = days - 1; i >= 0; i--) {
      const checkDate = new Date(today);
      checkDate.setDate(today.getDate() - i);
      const dateStr = getDateString(checkDate);
      const created = [
        ...this.plugin.data.dailyTasks,
        ...this.plugin.data.freeTasks
      ].filter((t) => getDateString(new Date(t.createdAt)) === dateStr).length;
      const completed = this.plugin.data.completions.filter((c) => c.date === dateStr).length;
      history.push({ date: dateStr, created, completed });
    }
    return history;
  }
  /**
   * Find the goal with the most completions in the last 7 days
   */
  getMostActiveGoal() {
    const sevenDaysAgo = Date.now() - 7 * 24 * 60 * 60 * 1e3;
    const goalCounts = {};
    this.plugin.data.completions.filter((c) => c.completedAt >= sevenDaysAgo && c.goalId).forEach((c) => {
      if (c.goalId) {
        goalCounts[c.goalId] = (goalCounts[c.goalId] || 0) + 1;
      }
    });
    let mostActiveId = null;
    let maxCount = 0;
    for (const [id, count] of Object.entries(goalCounts)) {
      if (count > maxCount) {
        maxCount = count;
        mostActiveId = id;
      }
    }
    return mostActiveId ? this.plugin.data.goals.find((g) => g.id === mostActiveId) || null : null;
  }
};

// studentManager.ts
var import_obsidian9 = require("obsidian");
var StudentManager = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  /**
   * Create a new unit
   */
  async createUnit(unitData) {
    const newUnit = {
      id: this.generateId(),
      name: unitData.name || "Untitled Unit",
      code: unitData.code || "",
      semester: unitData.semester || this.getCurrentSemester(),
      credits: unitData.credits || 0,
      status: "active",
      instructor: unitData.instructor,
      schedule: unitData.schedule || [],
      exams: unitData.exams || []
    };
    this.plugin.data.studentUnits.push(newUnit);
    await this.plugin.savePluginData();
    return newUnit;
  }
  /**
   * Delete a unit by ID
   */
  async deleteUnit(unitId) {
    const index = this.plugin.data.studentUnits.findIndex((u) => u.id === unitId);
    if (index !== -1) {
      this.plugin.data.studentUnits.splice(index, 1);
      await this.plugin.savePluginData();
    }
  }
  /**
   * Add an exam to a unit
   */
  async addExam(unitId, examData) {
    const unit = this.plugin.data.studentUnits.find((u) => u.id === unitId);
    if (!unit) {
      return null;
    }
    const newExam = {
      id: this.generateId(),
      unitId,
      title: examData.title || "Untitled Exam",
      date: examData.date || Date.now(),
      time: examData.time || "09:00",
      location: examData.location,
      topics: examData.topics || []
    };
    unit.exams.push(newExam);
    await this.plugin.savePluginData();
    return newExam;
  }
  /**
   * Delete an exam by ID
   */
  async deleteExam(unitId, examId) {
    const unit = this.plugin.data.studentUnits.find((u) => u.id === unitId);
    if (!unit)
      return;
    const examIndex = unit.exams.findIndex((e) => e.id === examId);
    if (examIndex !== -1) {
      unit.exams.splice(examIndex, 1);
      await this.plugin.savePluginData();
    }
  }
  /**
   * Get upcoming exams within the next N days
   */
  getUpcomingExams(daysAhead = 30) {
    if (!this.plugin.data.studentUnits) {
      return [];
    }
    const now = Date.now();
    const futureDate = now + daysAhead * 24 * 60 * 60 * 1e3;
    const allExams = [];
    for (const unit of this.plugin.data.studentUnits) {
      for (const exam of unit.exams) {
        if (exam.date >= now && exam.date <= futureDate) {
          allExams.push(exam);
        }
      }
    }
    return allExams.sort((a, b) => a.date - b.date);
  }
  /**
   * Get all units for the current semester
   */
  getCurrentSemesterUnits() {
    if (!this.plugin.data.studentUnits) {
      return [];
    }
    const currentSemester = this.getCurrentSemester();
    return this.plugin.data.studentUnits.filter((u) => u.semester === currentSemester && (u.status || "active") === "active");
  }
  async markUnitAsCompleted(unitId) {
    const unit = this.plugin.data.studentUnits.find((u) => u.id === unitId);
    if (unit) {
      unit.status = "completed";
      unit.completedDate = Date.now();
      await this.plugin.savePluginData();
      this.plugin.app.workspace.trigger("better-task:data-change");
      new import_obsidian9.Notice(`Unit "${unit.name}" marked as completed!`);
    }
  }
  async archiveUnit(unitId) {
    const unit = this.plugin.data.studentUnits.find((u) => u.id === unitId);
    if (unit) {
      unit.status = "archived";
      await this.plugin.savePluginData();
      this.plugin.app.workspace.trigger("better-task:data-change");
      new import_obsidian9.Notice(`Unit "${unit.name}" archived.`);
    }
  }
  /**
   * Get all units (for viewing all semesters)
   */
  getAllUnits() {
    return this.plugin.data.studentUnits;
  }
  /**
   * Get unit by ID
   */
  getUnitById(unitId) {
    return this.plugin.data.studentUnits.find((u) => u.id === unitId);
  }
  /**
   * Get exam by ID (searches across all units)
   */
  getExamById(examId) {
    if (!this.plugin.data.studentUnits) {
      return null;
    }
    for (const unit of this.plugin.data.studentUnits) {
      const exam = unit.exams.find((e) => e.id === examId);
      if (exam) {
        return { unit, exam };
      }
    }
    return null;
  }
  /**
   * Generate study tasks for an exam
   * Creates free tasks for each topic 2-3 days before the exam
   */
  async generateStudyTasks(examId) {
    const examInfo = this.getExamById(examId);
    if (!examInfo) {
      return [];
    }
    const { unit, exam } = examInfo;
    const createdTasks = [];
    const daysUntilExam = Math.floor((exam.date - Date.now()) / (24 * 60 * 60 * 1e3));
    const studyDaysBefore = Math.min(daysUntilExam, 3);
    for (let i = 0; i < exam.topics.length; i++) {
      const topic = exam.topics[i];
      const daysBeforeExam = Math.max(2, studyDaysBefore - i % studyDaysBefore);
      const dueDate = exam.date - daysBeforeExam * 24 * 60 * 60 * 1e3;
      const studyTask = {
        id: this.generateId(),
        title: `Study: ${unit.name} - ${topic}`,
        description: `Prepare for ${exam.title} on ${new Date(exam.date).toLocaleDateString()}`,
        dueDate,
        dueTime: "18:00",
        // Default study time
        isCompleted: false,
        reminderMinutes: 15,
        createdAt: Date.now()
      };
      this.plugin.data.freeTasks.push(studyTask);
      createdTasks.push(studyTask);
    }
    await this.plugin.savePluginData();
    this.plugin.app.workspace.trigger("better-task:data-change");
    return createdTasks;
  }
  /**
   * Determine current semester based on the current date
   * Common semester pattern: Spring (Jan-May), Summer (Jun-Aug), Fall (Sep-Dec)
   */
  getCurrentSemester() {
    const now = new Date();
    const month = now.getMonth();
    const year = now.getFullYear();
    if (month >= 0 && month <= 4) {
      return `Spring ${year}`;
    } else if (month >= 5 && month <= 7) {
      return `Summer ${year}`;
    } else {
      return `Fall ${year}`;
    }
  }
  /**
   * Generate a unique ID
   */
  generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
  }
  /**
   * Get days until an exam
   */
  getDaysUntilExam(exam) {
    const now = Date.now();
    const daysUntil = Math.ceil((exam.date - now) / (24 * 60 * 60 * 1e3));
    return daysUntil;
  }
  /**
   * Check if exam is in the past
   */
  isExamPast(exam) {
    return exam.date < Date.now();
  }
};

// modals/unitModal.ts
var import_obsidian10 = require("obsidian");
var UnitModal = class extends import_obsidian10.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.unitData = {};
    this.onSubmit = onSubmit;
  }
  onOpen() {
    this.renderContent();
  }
  renderContent() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Create New Unit" });
    new import_obsidian10.Setting(contentEl).setName("Unit Name").setDesc("Full name of the unit/course").addText((text) => text.setPlaceholder("e.g., Introduction to Computer Science").setValue(this.unitData.name || "").onChange((value) => {
      this.unitData.name = value;
    }));
    new import_obsidian10.Setting(contentEl).setName("Unit Code").setDesc("Course code or number").addText((text) => text.setPlaceholder("e.g., CS101").setValue(this.unitData.code || "").onChange((value) => {
      this.unitData.code = value;
    }));
    new import_obsidian10.Setting(contentEl).setName("Semester").setDesc("When this unit is taught").addText((text) => text.setPlaceholder("e.g., Fall 2026").setValue(this.unitData.semester || "").onChange((value) => {
      this.unitData.semester = value;
    }));
    new import_obsidian10.Setting(contentEl).setName("Credits").setDesc("Number of credit hours").addText((text) => {
      var _a;
      return text.setPlaceholder("e.g., 3").setValue(((_a = this.unitData.credits) == null ? void 0 : _a.toString()) || "").onChange((value) => {
        const credits = parseInt(value);
        this.unitData.credits = isNaN(credits) ? 0 : credits;
      });
    });
    new import_obsidian10.Setting(contentEl).setName("Instructor").setDesc("Professor or teacher name (optional)").addText((text) => text.setPlaceholder("e.g., Dr. Smith").setValue(this.unitData.instructor || "").onChange((value) => {
      this.unitData.instructor = value || void 0;
    }));
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container", attr: { style: "display: flex; gap: 10px; justify-content: flex-end; margin-top: 20px;" } });
    const cancelBtn = buttonContainer.createEl("button", {
      text: "Cancel"
    });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
    const addAnotherBtn = buttonContainer.createEl("button", {
      text: "Create & Add Another"
    });
    addAnotherBtn.addEventListener("click", () => {
      if (this.validateForm()) {
        this.onSubmit(this.unitData, false);
        const currentSemester = this.unitData.semester;
        this.unitData = { semester: currentSemester };
        this.renderContent();
      }
    });
    const submitBtn = buttonContainer.createEl("button", {
      text: "Create Unit",
      cls: "mod-cta"
    });
    submitBtn.addEventListener("click", () => {
      if (this.validateForm()) {
        this.onSubmit(this.unitData, true);
        this.close();
      }
    });
  }
  validateForm() {
    if (!this.unitData.name || !this.unitData.code) {
      new import_obsidian10.Notice("Please fill in unit name and code");
      return false;
    }
    return true;
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
init_examModal();

// modals/welcomeModal.ts
var import_obsidian11 = require("obsidian");
var WelcomeModal = class extends import_obsidian11.Modal {
  constructor(app, onCloseCallback) {
    super(app);
    this.onCloseCallback = onCloseCallback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("better-task-welcome-modal");
    contentEl.createEl("h1", { text: "Welcome to Better Task! \u{1F680}" });
    const introText = contentEl.createEl("div", { cls: "welcome-content" });
    introText.createEl("p", { text: "Your new productivity companion for Obsidian." });
    introText.createEl("h3", { text: "How it works:" });
    const steps = introText.createEl("ul");
    steps.createEl("li", { text: "\u{1F3AF} Create Goals to define what you want to achieve." });
    steps.createEl("li", { text: "\u{1F4C5} Add Daily Tasks linked to your goals." });
    steps.createEl("li", { text: "\u{1F525} Build Streaks and track your progress." });
    const note = introText.createEl("p", { cls: "student-note" });
    note.createEl("strong", { text: "\u{1F393} Student?" });
    note.createSpan({ text: " Student Mode is enabled by default! You can manage your courses and exams right away." });
    const btnContainer = contentEl.createEl("div", { cls: "welcome-actions" });
    const btn = btnContainer.createEl("button", { cls: "mod-cta", text: "Let's Get Started" });
    btn.onclick = () => {
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.onCloseCallback();
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  notificationsEnabled: true,
  streakWarningDays: 3,
  reminderSound: true,
  studentMode: true,
  hasSeenWelcome: false
};
var DEFAULT_DATA = {
  goals: [],
  dailyTasks: [],
  freeTasks: [],
  completions: [],
  studentUnits: [],
  settings: DEFAULT_SETTINGS
};
var BetterTaskPlugin = class extends import_obsidian12.Plugin {
  constructor() {
    super(...arguments);
    // Undo/Redo stacks (in-memory only, not persisted)
    this.undoStack = [];
    this.redoStack = [];
  }
  async onload() {
    console.log("Loading Better Task plugin");
    await this.loadPluginData();
    this.goalManager = new GoalManager(this);
    this.taskManager = new TaskManager(this);
    this.notificationManager = new NotificationManager(this);
    this.analyticsManager = new AnalyticsManager(this);
    this.studentManager = new StudentManager(this);
    this.notificationManager.startBackgroundCheck();
    if (!this.data.settings.hasSeenWelcome) {
      new WelcomeModal(this.app, async () => {
        this.data.settings.hasSeenWelcome = true;
        await this.savePluginData();
        this.activateView();
      }).open();
    }
    this.registerView(
      DASHBOARD_VIEW_TYPE,
      (leaf) => new DashboardView(leaf, this)
    );
    this.addRibbonIcon("check-circle", "Better Task", (evt) => {
      this.activateView();
    });
    this.addSettingTab(new BetterTaskSettingTab(this.app, this));
    this.addCommand({
      id: "open-dashboard",
      name: "Open Dashboard",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "create-goal",
      name: "Create New Goal",
      callback: () => {
        new GoalModal(this.app, async (result) => {
          await this.goalManager.createGoal(result.title, result.description);
        }).open();
      }
    });
    this.addCommand({
      id: "create-daily-task",
      name: "Create Daily Task",
      callback: () => {
        if (this.data.goals.length === 0) {
          new import_obsidian12.Notice("Please create a goal first!");
          return;
        }
        new TaskModal(this, "daily", this.data.goals, async (result) => {
          if (result.goalId) {
            await this.taskManager.createDailyTask(result.goalId, result);
          } else {
            new import_obsidian12.Notice("No goal selected!");
          }
        }).open();
      }
    });
    this.addCommand({
      id: "create-free-task",
      name: "Create Quick Task",
      callback: () => {
        new TaskModal(this, "free", [], async (result) => {
          await this.taskManager.createFreeTask(result);
        }).open();
      }
    });
    this.addCommand({
      id: "create-unit",
      name: "Create Unit/Course",
      callback: () => {
        if (!this.data.settings.studentMode) {
          new import_obsidian12.Notice("Please enable Student Mode in settings first!");
          return;
        }
        new UnitModal(this.app, async (unitData, shouldClose) => {
          const unit = await this.studentManager.createUnit(unitData);
          new import_obsidian12.Notice(`Unit "${unit.name}" created!`);
          this.app.workspace.trigger("better-task:data-change");
        }).open();
      }
    });
    this.addCommand({
      id: "add-exam",
      name: "Add Exam",
      callback: () => {
        if (!this.data.settings.studentMode) {
          new import_obsidian12.Notice("Please enable Student Mode in settings first!");
          return;
        }
        if (this.data.studentUnits.length === 0) {
          new import_obsidian12.Notice("Please create a unit first!");
          return;
        }
        new UnitSuggestModal(this.app, this.data.studentUnits, (unit) => {
          new ExamModal(this.app, unit, async (examData) => {
            const exam = await this.studentManager.addExam(unit.id, examData);
            if (exam) {
              new import_obsidian12.Notice(`Exam "${exam.title}" added!`);
              this.app.workspace.trigger("better-task:data-change");
            }
          }).open();
        }).open();
      }
    });
    this.addCommand({
      id: "undo-action",
      name: "Undo",
      hotkeys: [{ modifiers: ["Mod"], key: "z" }],
      callback: () => {
        this.undo();
      }
    });
    this.addCommand({
      id: "redo-action",
      name: "Redo",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "z" }],
      callback: () => {
        this.redo();
      }
    });
  }
  onunload() {
    var _a;
    console.log("Unloading Better Task plugin");
    (_a = this.notificationManager) == null ? void 0 : _a.stopBackgroundCheck();
  }
  async loadPluginData() {
    this.data = Object.assign({}, DEFAULT_DATA, await this.loadData());
  }
  async savePluginData() {
    await this.saveData(this.data);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(DASHBOARD_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeaf(true);
      await leaf.setViewState({ type: DASHBOARD_VIEW_TYPE, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  /**
   * Save current state to undo stack before making changes
   * Clears redo stack since new actions invalidate redo history
   */
  saveToUndoStack(action, previousState) {
    const entry = {
      action,
      previousState,
      timestamp: Date.now()
    };
    this.undoStack.push(entry);
    if (this.undoStack.length > 20) {
      this.undoStack.shift();
    }
    this.redoStack = [];
  }
  /**
   * Undo the last action
   */
  async undo() {
    if (this.undoStack.length === 0) {
      new import_obsidian12.Notice("Nothing to undo");
      return;
    }
    const entry = this.undoStack.pop();
    const currentState = this.captureCurrentState(entry.action, entry.previousState);
    this.redoStack.push({
      action: entry.action,
      previousState: currentState,
      timestamp: Date.now()
    });
    await this.restoreState(entry.action, entry.previousState);
    new import_obsidian12.Notice(`Undone: ${this.getActionLabel(entry.action)}`);
  }
  /**
   * Redo the last undone action
   */
  async redo() {
    if (this.redoStack.length === 0) {
      new import_obsidian12.Notice("Nothing to redo");
      return;
    }
    const entry = this.redoStack.pop();
    const currentState = this.captureCurrentState(entry.action, entry.previousState);
    this.undoStack.push({
      action: entry.action,
      previousState: currentState,
      timestamp: Date.now()
    });
    await this.restoreState(entry.action, entry.previousState);
    new import_obsidian12.Notice(`Redone: ${this.getActionLabel(entry.action)}`);
  }
  /**
   * Capture current state for redo
   */
  captureCurrentState(action, previousState) {
    switch (action) {
      case "goal_created": {
        const goalId = previousState.goalId;
        const goal = this.data.goals.find((g) => g.id === goalId);
        return { goal: goal ? { ...goal } : null };
      }
      case "goal_deleted":
        return {};
      case "daily_task_created": {
        const taskId = previousState.taskId;
        const task = this.data.dailyTasks.find((t) => t.id === taskId);
        return { task: task ? { ...task } : null };
      }
      case "free_task_created": {
        const freeTaskId = previousState.taskId;
        const freeTask = this.data.freeTasks.find((t) => t.id === freeTaskId);
        return { freeTask: freeTask ? { ...freeTask } : null };
      }
      case "task_completed": {
        const completionTaskId = previousState.taskId;
        const completion = this.data.completions.find((c) => c.taskId === completionTaskId && c.date === new Date().toISOString().split("T")[0]);
        const completedFreeTask = previousState.freeTask ? this.data.freeTasks.find((t) => t.id === completionTaskId) : null;
        return {
          completion: completion ? { ...completion } : null,
          freeTask: completedFreeTask ? { ...completedFreeTask } : null
        };
      }
      default:
        return {};
    }
  }
  /**
   * Restore state from undo/redo entry
   */
  async restoreState(action, state) {
    const goalId = state.goalId;
    const goal = state.goal;
    const tasks = state.tasks;
    const taskId = state.taskId;
    const freeTask = state.freeTask;
    switch (action) {
      case "goal_created":
        if (goalId) {
          this.data.goals = this.data.goals.filter((g) => g.id !== goalId);
        }
        break;
      case "goal_deleted":
        if (goal) {
          this.data.goals.push(goal);
        }
        if (tasks && Array.isArray(tasks)) {
          this.data.dailyTasks.push(...tasks);
        }
        break;
      case "daily_task_created":
        if (taskId) {
          this.data.dailyTasks = this.data.dailyTasks.filter((t) => t.id !== taskId);
        }
        break;
      case "free_task_created":
        if (taskId) {
          this.data.freeTasks = this.data.freeTasks.filter((t) => t.id !== taskId);
        }
        break;
      case "task_completed":
        if (taskId) {
          const today = new Date().toISOString().split("T")[0];
          this.data.completions = this.data.completions.filter(
            (c) => !(c.taskId === taskId && c.date === today)
          );
          if (freeTask) {
            const ft = this.data.freeTasks.find((t) => t.id === taskId);
            if (ft) {
              ft.isCompleted = false;
              ft.completedAt = void 0;
            }
          }
        }
        break;
    }
    await this.savePluginData();
    this.app.workspace.trigger("better-task:data-change");
  }
  /**
   * Get human-readable label for action
   */
  getActionLabel(action) {
    const labels = {
      "goal_created": "Create goal",
      "goal_deleted": "Delete goal",
      "daily_task_created": "Create daily task",
      "free_task_created": "Create quick task",
      "task_completed": "Complete task"
    };
    return labels[action] || action;
  }
};
var BetterTaskSettingTab = class extends import_obsidian12.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Better Task Settings" });
    new import_obsidian12.Setting(containerEl).setName("Enable notifications").setDesc("Show reminders for upcoming tasks").addToggle((toggle) => toggle.setValue(this.plugin.data.settings.notificationsEnabled).onChange(async (value) => {
      this.plugin.data.settings.notificationsEnabled = value;
      await this.plugin.savePluginData();
    }));
    new import_obsidian12.Setting(containerEl).setName("Notification sound").setDesc("Play sound with notifications").addToggle((toggle) => toggle.setValue(this.plugin.data.settings.reminderSound).onChange(async (value) => {
      this.plugin.data.settings.reminderSound = value;
      await this.plugin.savePluginData();
    }));
    new import_obsidian12.Setting(containerEl).setName("Streak warning threshold").setDesc("Show warning after missing this many days").addSlider((slider) => slider.setLimits(1, 30, 1).setValue(this.plugin.data.settings.streakWarningDays).setDynamicTooltip().onChange(async (value) => {
      this.plugin.data.settings.streakWarningDays = value;
      await this.plugin.savePluginData();
    }));
    new import_obsidian12.Setting(containerEl).setName("Student Mode").setDesc("Enable semester tracking and exam scheduling").addToggle((toggle) => toggle.setValue(this.plugin.data.settings.studentMode).onChange(async (value) => {
      this.plugin.data.settings.studentMode = value;
      await this.plugin.savePluginData();
      this.plugin.app.workspace.trigger("better-task:data-change");
    }));
  }
};
var UnitSuggestModal = class extends import_obsidian12.FuzzySuggestModal {
  constructor(app, units, onChoose) {
    super(app);
    this.units = units;
    this.onChoose = onChoose;
  }
  getItems() {
    return this.units;
  }
  getItemText(unit) {
    return `${unit.code} - ${unit.name}`;
  }
  onChooseItem(unit, evt) {
    this.onChoose(unit);
  }
};
